name: End-to-end Tests
on: [push] # Runs on every push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # Executes the Cypress tests
          command: npx cypress run --browser chrome
         
          # Generates Mochawesome JSON reports for each test run
      - name: Upload Test Report
        if: always() # Ensures reports are uploaded even if a test fails
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/html/